import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Navbar from "~/components/Navbar";
import { Hero } from "~/components/Hero";
import { FourProducts } from "~/components/HomeScreen/FourProducts";
import { ImageGrid } from "~/components/HomeScreen/ImageGrid";
import { ImageGrid2 } from "~/components/HomeScreen/ImageGrid2";
import { Image } from "@chakra-ui/react";
import { ImageCard } from "~/components/HomeScreen/ImageCard";
import { BoxText } from "~/components/HomeScreen/BoxText";
import { CategoryImagesGrid } from "~/components/HomeScreen/CategoryImagesGrid";
import ReviewCarousel from "~/components/HomeScreen/ReviewCarousel";
import ProductList from "~/components/Products/ProductList";
import Footer from "~/components/footer"


const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="" />
      </Head>
      <main>
        <div>
          <div>
            <Hero />
          </div>
          <div>
            <FourProducts />
          </div>
          <div>
            <ImageGrid />
          </div>
          <div>
            <ImageGrid2 />
          </div>
          <div>
            <ImageCard />
          </div>
          <div>
            <BoxText />
          </div>
          <div>
            <CategoryImagesGrid />
          </div>
          <div></div>
        </div>
      </main>
    </>
  );
};

export default Home;

export const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
